name: start workflow
on:
  push: 
    branches:
      - main
jobs:
  Hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hellow Master
        run: echo "Hello World!"

      - name: Build pipeline
        run: echo "Building and pushing when push is made to main branch"